app = "quiet-meadow-6897"

[build]
image = "ghcr.io/tfausak/advent-of-code-2022:latest"

[[services]]
internal_port = 80
protocol = "tcp"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
