on: push
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
      - run: dotnet test
      - run: dotnet tool restore
      - run: dotnet fantomas --check --recurse .
      - run: dotnet fsharplint lint AdventOfCode.sln
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v3
