on: push
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
      - run: dotnet test
      - run: dotnet tool restore
      - run: dotnet fantomas --check --recurse .
      - run: dotnet fsharplint lint AdventOfCode.sln
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=false
          tags: type=sha,format=long
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --image ${{ steps.meta.outputs.tags }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
